apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  targetType: ip
  serviceRef:
    name: frontend 
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:166557488034:targetgroup/alb-tg/cdddbfb5b7d03a58